### ISSUE TITLE
Always show auto complete without having to press Tab like in Rofi and dmenu

### ISSUE THREAD

**Issue by ghost** [phillbush/xprompt#6]

**Comment by phillbush** [comment]
I added a `-c` option to show auto complete without having to press Tab.
Unfortunately, because of how completion works (it is encapsulated in the `keypress()` function) you need to press a key (not necessarily Tab) in order for the completion to be activated. So you must start typing something for xprompt to filter the completions.

**Comment by aspizu** [comment]
this isn't documented.

**Comment by Veraellyunjie** [comment]
> Unfortunately, because of how completion works (it is encapsulated in the keypress() function) you need to press a key (not necessarily Tab) in order for the completion to be activated. So you must start typing something for xprompt to filter the completions.

How hard and worthwhile a fix would be?
With `dmenu`, you can just press `Return` to select the 1st item.
Plays nice when e.g. items are pre-sorted by frecency - most-used item doesn't require typing
